

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NotesAppSqlServer.DataLayer.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class NotesAppContext : DbContext
{
    public NotesAppContext()
        : base("name=NotesAppContext")
    {

    }

    //protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //{
    //    throw new UnintentionalCodeFirstException();
    //}


    public virtual DbSet<Note> Notes { get; set; }

}

}

